### ISSUE TITLE
Associated gui button for json report downloading

### ISSUE THREAD

**Issue by niapoor** [cisagov/mesa-gui#10]
# 💡 Summary #

This work creates an associated button for downloading json reports of mesa scan results.

## Motivation and context ##

There is a need for a gui implementation to download json reports of mesa scan results. Without this, the user will have no easy way of downloading json reports.

## Implementation notes ##

* Use this by selecting the "Download JSON Report" button in the mesa gui and observing the associated output files.
* This issue is connected to the following issue in the mesa toolkit: https://github.com/cisagov/mesa-toolkit/issues/16

## Acceptance criteria ##

How do we know when this work is done?

- [x] The "Download JSON Report" button successfully downloads the json report in the report directory of the downloaded zip file.

**Comment by niapoor** [comment]
Since my changes are accessible via the gui, I was able to test and validate them through there.
- I validated my JSON button addition worked by pressing the "Download JSON Report" button, unzipping the downloaded file, and navigating to the json file in the json directory. I knew it worked if the json file had been successfully created as a result of selecting that button.

**Comment by m1j09830** [comment]
This issue is satisfied by #15
