### ISSUE TITLE
MESA-GUI update to remove domain enumeration related flags

### ISSUE THREAD

**Issue by CyberDoug** [cisagov/mesa-gui#7]
# 💡 Summary #

The MESA domain enumeration scans were removed. This facilitated the need to remove domain enumeration related flags from the GUI from end.

## Motivation and context ##

The domain enumeration flags are no longer necessary as a result of the removal of the domain enumeration scans.

## Implementation notes ##

Please provide details for implementation, such as:

Remove the following variables and their references from the entire code base:
- domain_fqdn
- domain_controller
- domain_password
- neo4j_user
- neo4j_password

## Acceptance criteria ##

How do we know when this work is done?

- [x] The MESA-GUI works without error and as expected.

**Comment by m1j09830** [comment]
This issue was satisfied by PR #8
